# Generated by Django 4.0.3 on 2022-04-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='creativity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='developer',
            field=models.IntegerField(default=0),
        ),
    ]
