# Generated by Django 4.0.3 on 2022-04-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_rating_creativity_rating_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, max_length=2555),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.IntegerField(choices=[(1, '1-Trash'), (2, '2-Horrible'), (3, '3-Terrible'), (4, '4-Bad'), (5, '5- ok'), (6, '6-Well'), (7, '7-Good'), (8, '8-Very Good'), (9, '9-Excellent'), (10, '10-Perfect')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='creativity',
            field=models.IntegerField(choices=[(1, '1-Trash'), (2, '2-Horrible'), (3, '3-Terrible'), (4, '4-Bad'), (5, '5- ok'), (6, '6-Well'), (7, '7-Good'), (8, '8-Very Good'), (9, '9-Excellent'), (10, '10-Perfect')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(choices=[(1, '1-Trash'), (2, '2-Horrible'), (3, '3-Terrible'), (4, '4-Bad'), (5, '5- ok'), (6, '6-Well'), (7, '7-Good'), (8, '8-Very Good'), (9, '9-Excellent'), (10, '10-Perfect')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='developer',
            field=models.IntegerField(choices=[(1, '1-Trash'), (2, '2-Horrible'), (3, '3-Terrible'), (4, '4-Bad'), (5, '5- ok'), (6, '6-Well'), (7, '7-Good'), (8, '8-Very Good'), (9, '9-Excellent'), (10, '10-Perfect')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(choices=[(1, '1-Trash'), (2, '2-Horrible'), (3, '3-Terrible'), (4, '4-Bad'), (5, '5- ok'), (6, '6-Well'), (7, '7-Good'), (8, '8-Very Good'), (9, '9-Excellent'), (10, '10-Perfect')], default=0),
        ),
    ]
