# Generated by Django 4.0.3 on 2022-04-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='rate.profile'),
        ),
    ]
