# Generated by Django 4.0.3 on 2022-04-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_rating_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='profile',
        ),
    ]
